savvystripe/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from profiles import views as profile_views
from contact import views as contact_views
from checkout import views as checkout_views
from customers import views as customer_views
from checkout.models import Item, Service
from customers.models import stripeEvent
# import notifications.urls

urlpatterns = [
    url(r'^$', profile_views.home, name='home'),
    url(r'^accounts/', include('allauth.urls'), name='accounts'),
    # url(r'^carton/', include('carton.urls')),
    url(r'^about/$', profile_views.about, name='about'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^billing/$', customer_views.billing_view, name='billing'),
    url(r'^capture/$', checkout_views.capture, name='capture'),
    url(r'^add-to-cart/$', checkout_views.add_to_cart, name='add-to-cart' ),
    url(r'^add-subscription/$', checkout_views.add_subscription, name='add-subscription'),
    url(r'^remove-subscription/$', checkout_views.remove_subscription, name='remove-subscription'),
    # url(r'^cart-subscribe/$', checkout_views.cart_subscribe, name='cart-subscribe'),
    url(r'^unsubscribe/$', checkout_views.unsubscribe, name='ubsubscribe'),
    url(r'^subscribe/$', checkout_views.subscribe, name='subscribe'),
    url(r'^subscribe-card/$', checkout_views.subscribe_savecard, name='subscribe-card'),
    url(r'^remove-from-cart/$', checkout_views.remove_from_cart, name='remove-from-cart'),
    url(r'^before-checkout/$', checkout_views.before_checkout, name='before-checkout'),
    url(r'^cart/$', checkout_views.get_cart, name='cart'),
    url(r'^cart-total/$', checkout_views.get_cart_total, name='cart-total'),
    url(r'^checkout/$', checkout_views.checkout, name='checkout'),
    url(r'^hook/$', customer_views.event_hook, name='hook'),
    url(r'^checkout-thanks/$', checkout_views.checkoutThanks, name='checkoutThanks'),
    url(r'^contact/$', contact_views.contact, name='contact'),
    url(r'^contact/i', contact_views.contact, name='contact_track'),
    url(r'^dashboard/', include('dashboard.urls'), name='dashboard'),
    url(r'^domains/$', contact_views.searchDomains, name='domains'),
    url(r'^domain-results/$', contact_views.resultDomains, name='domain-results'),
    # url(r'^admin_dashboard/$', customer_views.admin_dashboard, name='admin_dashboard'),
    url(r'^events/$', customer_views.EventList, name='events'),
    url(r'^email_history/$', customer_views.email_history_view, name='email_history'),
    url(r'^inbox/notifications/', include("notifications.urls", namespace='notifications')) ,
    url(r'^articles/$', customer_views.KBListView.as_view(), name='articles'),
    url(r'^articles/(?P<pk>\d+)/$', customer_views.KBDetailView.as_view(), name='article'),
    url(r'^invoices/$', customer_views.my_invoices, name='invoices'),
    # url(r'^pixel/', include('pixel_tracker.urls'), name='pixels'),
    #url(r'^tracker/', include('django_pixels.urls', namespace="pixels")),
    url(r'^profile/$', profile_views.userProfile, name='profile'),
    # url(r'^sales/', include("sales.urls", namespace='sales')) ,
    url(r'^services/$', checkout_views.ServiceListView.as_view(), name='services'),
    url(r'^services/(?P<pk>\d+)/$', checkout_views.ServiceDetailView.as_view(), name='service'),
    # ex: /items/5/
    url(r'^my_services/$', customer_views.my_services, name='my_services'),
    url(r'^products/$', checkout_views.ItemListView.as_view(), name='items'),

    url(r'^products/(?P<pk>\d+)/$', checkout_views.ItemDetailView.as_view(), name='item'),
    # ex: /items/5/purchased/
    url(r'^tickets/', include("tickets.urls"), name='tickets') ,
    
]
    

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

savvystripe/sales/urls.py
from django.conf.urls import *
from sales import views

urlpatterns = [
    url(r'^charge/$', views.charge, name="charge"),
]

savvystripe/profiles/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from allauth.account.signals import user_logged_in, user_signed_up
import stripe


stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your models here.
class profile(models.Model):
	

	'''
	Profile object to integrate django user with stripe customer
	'''
	# def __init__(self):
	# 	self.name = ''
	# 	self.email = ''

	name = models.CharField(max_length=120)
	user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, blank=True)
	description = models.TextField(default='description default text')
	email = models.CharField(max_length=50, null=True, blank=True)
	# stripe_id = models.ForeignKey(stripeCustomer, null=True, blank=True)

	def __str__(self):
		return self.user.email

	def __unicode__(self):
		return str(self.user.email)

class userStripe(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	stripe_id = models.CharField(max_length=200, null=True, blank=True)

	def delete(self, *args, **kwargs):
        	cu = stripe.Customer.retrieve(self.stripe_id)
        	cu.delete()
        	super(userStripe, self).delete(*args, **kwargs)    

	def __unicode__(self):
		if self.stripe_id:
			return str(self.stripe_id)
		else: 
			return self.user.username

	def __str__(self):
		if self.stripe_id:
			return str(self.stripe_id)
		else: 
			return self.user.username

    	# def save(self, *args, **kwargs):
     #    	s = stripeCustomer.objects.create(user=self.user, sid=self.stripe_id)
     #    	super(userStripe, self).save(*args, **kwargs)

def stripeCallback(sender, request, user, **kwargs):
	user_stripe_account, created = userStripe.objects.get_or_create(user=user)
	if created:
		print 'created for %s' % user.username
	if user_stripe_account.stripe_id is None or user_stripe_account.stripe_id == '':
		desc = "Portal User: %s" % user.username
		new_stripe_id = stripe.Customer.create(description=desc,email=user.email)
		user_stripe_account.stripe_id = new_stripe_id['id']
		user_stripe_account.save()

def profileCallback(sender, request, user, **kwargs):
	userProfile, is_created = profile.objects.get_or_create(user=user)
	if is_created:
		userProfile.name = user.username
		userProfile.email = user.email
		userProfile.save()

user_logged_in.connect(stripeCallback)
user_signed_up.connect(profileCallback)
user_signed_up.connect(stripeCallback)

savvystripe/profiles/forms.py
from __future__ import absolute_import
from captcha.fields import ReCaptchaField

import warnings
from importlib import import_module

from django import forms
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core import exceptions, validators
from django.utils.translation import pgettext, ugettext, ugettext_lazy as _

from allauth.account import app_settings
from allauth.compat import reverse
from allauth.utils import (
    build_absolute_uri,
    get_username_max_length,
    set_form_field_order,
)
from allauth.account.adapter import get_adapter
from allauth.account.app_settings import AuthenticationMethod
from allauth.account.models import EmailAddress
from allauth.account.utils import (
    filter_users_by_email,
    get_user_model,
    perform_login,
    setup_user_email,
    url_str_to_user_pk,
    user_email,
    user_pk_to_url_str,
    user_username,
)

from simplemathcaptcha.fields   import MathCaptchaField
from simplemathcaptcha.fields import MathCaptchaField
from simplemathcaptcha.widgets import MathCaptchaWidget

class AllauthSignupForm(forms.Form):
    # captcha = ReCaptchaField()

    def signup(self, request, user):
        pass   



# class ContactForm(Form, FormMixin):
#     captcha = MathCaptchaField()



class PasswordVerificationMixin(object):
    def clean(self):
        cleaned_data = super(PasswordVerificationMixin, self).clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if (password1 and password2) and password1 != password2:
            self.add_error(
                'password2', _("You must type the same password each time.")
            )
        return cleaned_data


class PasswordField(forms.CharField):

    def __init__(self, *args, **kwargs):
        render_value = kwargs.pop('render_value',
                                  app_settings.PASSWORD_INPUT_RENDER_VALUE)
        kwargs['widget'] = forms.PasswordInput(render_value=render_value,
                                               attrs={'placeholder':
                                                      _(kwargs.get("label"))})
        super(PasswordField, self).__init__(*args, **kwargs)


class SetPasswordField(PasswordField):

    def __init__(self, *args, **kwargs):
        super(SetPasswordField, self).__init__(*args, **kwargs)
        self.user = None

    def clean(self, value):
        value = super(SetPasswordField, self).clean(value)
        value = get_adapter().clean_password(value, user=self.user)
        return value


class LoginForm(forms.Form):

    password = PasswordField(label=_("Password"))
    remember = forms.BooleanField(label=_("Remember Me"),
                                  required=False)

    user = None
    error_messages = {
        'account_inactive':
        _("This account is currently inactive."),

        'email_password_mismatch':
        _("The e-mail address and/or password you specified are not correct."),

        'username_password_mismatch':
        _("The username and/or password you specified are not correct."),

        'username_email_password_mismatch':
        _("The login and/or password you specified are not correct.")
    }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(LoginForm, self).__init__(*args, **kwargs)
        if app_settings.AUTHENTICATION_METHOD == AuthenticationMethod.EMAIL:
            login_widget = forms.TextInput(attrs={'type': 'email',
                                                  'placeholder':
                                                  _('E-mail address'),
                                                  'autofocus': 'autofocus'})
            login_field = forms.EmailField(label=_("E-mail"),
                                           widget=login_widget)
        elif app_settings.AUTHENTICATION_METHOD \
                == AuthenticationMethod.USERNAME:
            login_widget = forms.TextInput(attrs={'placeholder':
                                                  _('Username'),
                                                  'autofocus': 'autofocus'})
            login_field = forms.CharField(
                label=_("Username"),
                widget=login_widget,
                max_length=get_username_max_length())
        else:
            assert app_settings.AUTHENTICATION_METHOD \
                == AuthenticationMethod.USERNAME_EMAIL
            login_widget = forms.TextInput(attrs={'placeholder':
                                                  _('Username or e-mail'),
                                                  'autofocus': 'autofocus'})
            login_field = forms.CharField(label=pgettext("field label",
                                                         "Login"),
                                          widget=login_widget)
        self.fields["login"] = login_field
        set_form_field_order(self, ["login", "password", "remember"])
        if app_settings.SESSION_REMEMBER is not None:
            del self.fields['remember']

    def user_credentials(self):
        """
        Provides the credentials required to authenticate the user for
        login.
        """
        credentials = {}
        login = self.cleaned_data["login"]
        if app_settings.AUTHENTICATION_METHOD == AuthenticationMethod.EMAIL:
            credentials["email"] = login
        elif (
                app_settings.AUTHENTICATION_METHOD ==
                AuthenticationMethod.USERNAME):
            credentials["username"] = login
        else:
            if "@" in login and "." in login:
                credentials["email"] = login
            credentials["username"] = login
        credentials["password"] = self.cleaned_data["password"]
        return credentials

    def clean_login(self):
        login = self.cleaned_data['login']
        return login.strip()

    def clean(self):
        super(LoginForm, self).clean()
        if self._errors:
            return
        credentials = self.user_credentials()
        user = get_adapter(self.request).authenticate(
            self.request,
            **credentials)
        if user:
            self.user = user
        else:
            raise forms.ValidationError(
                self.error_messages[
                    '%s_password_mismatch'
                    % app_settings.AUTHENTICATION_METHOD])
        return self.cleaned_data

    def login(self, request, redirect_url=None):
        ret = perform_login(request, self.user,
                            email_verification=app_settings.EMAIL_VERIFICATION,
                            redirect_url=redirect_url)
        remember = app_settings.SESSION_REMEMBER
        if remember is None:
            remember = self.cleaned_data['remember']
        if remember:
            request.session.set_expiry(app_settings.SESSION_COOKIE_AGE)
        else:
            request.session.set_expiry(0)
        return ret


class _DummyCustomSignupForm(forms.Form):

    def signup(self, request, user):
        """
        Invoked at signup time to complete the signup of the user.
        """
        pass


def _base_signup_form_class():
    """
    Currently, we inherit from the custom form, if any. This is all
    not very elegant, though it serves a purpose:

    - There are two signup forms: one for local accounts, and one for
      social accounts
    - Both share a common base (BaseSignupForm)

    - Given the above, how to put in a custom signup form? Which form
      would your custom form derive from, the local or the social one?
    """
    if not app_settings.SIGNUP_FORM_CLASS:
        return _DummyCustomSignupForm
    try:
        fc_module, fc_classname = app_settings.SIGNUP_FORM_CLASS.rsplit('.', 1)
    except ValueError:
        raise exceptions.ImproperlyConfigured('%s does not point to a form'
                                              ' class'
                                              % app_settings.SIGNUP_FORM_CLASS)
    try:
        mod = import_module(fc_module)
    except ImportError as e:
        raise exceptions.ImproperlyConfigured('Error importing form class %s:'
                                              ' "%s"' % (fc_module, e))
    try:
        fc_class = getattr(mod, fc_classname)
    except AttributeError:
        raise exceptions.ImproperlyConfigured('Module "%s" does not define a'
                                              ' "%s" class' % (fc_module,
                                                               fc_classname))
    if not hasattr(fc_class, 'signup'):
        if hasattr(fc_class, 'save'):
            warnings.warn("The custom signup form must offer"
                          " a `def signup(self, request, user)` method",
                          DeprecationWarning)
        else:
            raise exceptions.ImproperlyConfigured(
                'The custom signup form must implement a "signup" method')
    return fc_class


class BaseSignupForm(_base_signup_form_class()):
    username = forms.CharField(label=_("Username"),
                               min_length=app_settings.USERNAME_MIN_LENGTH,
                               widget=forms.TextInput(
                                   attrs={'placeholder':
                                          _('Username'),
                                          'autofocus': 'autofocus'}))
    email = forms.EmailField(widget=forms.TextInput(
        attrs={'type': 'email',
               'placeholder': _('E-mail address')}))
    # captcha = ReCaptchaField()

    def __init__(self, *args, **kwargs):
        email_required = kwargs.pop('email_required',
                                    app_settings.EMAIL_REQUIRED)
        self.username_required = kwargs.pop('username_required',
                                            app_settings.USERNAME_REQUIRED)
        super(BaseSignupForm, self).__init__(*args, **kwargs)

savvystripe/profiles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import sessions
import json
from django.template import Context
from .models import userStripe
from django.conf import settings
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


# Create your views here.
def home(request):
	# cartitems = request.session['cart_items']
	context = {}
	template = 'home.html'
	return render(request, template, context)

def about(request):
	context = {}
	template = 'about.html'
	return render(request, template, context)

@login_required
def userProfile(request):
	# cartitems = request.session['cart_items']
	user = request.user
	customer_id = request.user.userstripe.stripe_id
	c = stripe.Charge.list(customer=customer_id)
	d = json.loads(str(c))
	data_list = d['data']
	context = {'user':user, 'data_list': data_list}
	template = 'profile.html'
	return render(request, template, context)

savvystripe/profiles/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1> Hello About </h1>
{% endblock %}

savvystripe/profiles/templates/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../favicon.ico"> -->

    <title>Savant Digital - Payment Portal</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet">
    {% url 'account_signup' as account_signup %}
    {% if request.path == account_signup %}
    <script src='https://www.google.com/recaptcha/api.js'></script>
    {% endif %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

<!--    {% url 'accounts' as accounts %}
  {% if request.path == accounts %} 
   <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '567668363440981',
      xfbml      : true,
      version    : 'v2.8'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
      function onButtonClick() {
      // Add this to a button's onclick handler
      FB.AppEvents.logEvent("sentFriendRequest");
    };
   </script>
   {% endif %} -->

    {% include 'navbar.html' %}
    
    <div class="container theme-showcase" role="main">
    {% block jumbotron %}
    {% endblock %}

    {% block content %}
    {% endblock %}
      
    {% block styles %}
    {% endblock %}


      

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<!-- <script type="text/javascript" src="https://js.stripe.com/v3/"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script> -->
    <script src="{% static 'javascript/bootstrap.min.js' %}"></script>
    {% block script %}

    {% endblock %}

{#    <script>#}
{#    $(document).ready(function(){#}
{#    {% block jquery %}#}
{#    {% endblock %}#}
{#    });#}
{#    </script>#}
  </body>
</html>

savvystripe/profiles/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
<style>
.jumbotron {
	text-align: center;
}
</style>
{% endblock %}

{% block jumbotron %}
<div class="row">
<div class="col-md-8 col-md-offset-3">
          <p class="text-center"><img src="{% static 'img/logo.jpg' %}" class="img-responsive"/></p>
       </div></div>

<div class="jumbotron">
        <h2>Savant Payment Portal</h2>
        <p>This is an area where you can sign into the portal by email address to view previous or outstanding subscription fees.</p>
      </div>
{% endblock %}

{% block content %}


<div class="row">
        <div class="col-md-4">
        {% if request.user.is_authenticated %}
        <h2 class="text-center">Account Links:</h2>
        <p class="text-center">
        <a class="btn btn-primary" href="{% url 'billing' %}"> Billing </a>
        <a class="btn btn-success" href="{% url 'my-tickets' %}"> Tickets </a> 
        <a class="btn btn-info" href="{% url 'articles' %}">Knowledgebase</a> 
        </p>
        {% else %}
          <h3 class='text-center'>Log in or Sign up</h3>
          <form class="login" method="POST" action="{% url 'account_login' %}">
          {% csrf_token %}

        <div class="input-group input-group-lg">
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-envelope"></span>
          </span>
          <input class="form-control" type="text" placeholder="Username or Email Address" required="true" name="login">
        </div>
        <div class="input-group input-group-lg">
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-lock"></span>
          </span>
          <input class="form-control" type="password" name="password" placeholder="Password">
        </div> 
        <p class="text-center">
          <div class="text-center" style="margin:20px">
          <span class="checkbox"></span>
          <input class="checkboxinput" id="id_remember" name="remember" type="checkbox"> Remember Me</label> 
          <span style="margin:20px" class="text-right"><button class="btn btn-primary  primaryAction" type="submit">Sign In</button></span>
          </div>
        </p>
        <div class="btn-group btn-group-justified">
        <p class="text-center">
          <a class="btn btn-default button secondaryAction" href="{% url 'account_reset_password' %}">Forgot Password?</a>
          <a class="btn btn-default button secondaryAction" href="{% url 'account_signup' %}">Signup</a>
        </p>
        </div>
        </form>
{% endif %}
      </div>      
        <div class="col-md-4">
          <h2>Announcements</h2>
          <p>Announcements placeholder </p>
          <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-md-4">
          <h2>Network Status</h2>
          <p> Status Placeholder</p>
       </div>
        
{% endblock %}

savvystripe/profiles/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
<div class="col-lg-12">
<h2 class="text-center">User Profile</h2> 
{% if user.first_name and user.last_name != None %}
<h3>Welcome {{ user.first_name }} {{ user.last_name }}</h3>
<hr />
{% endif %} 
<h4>Username: {{ user.username }}</h4>
<h4>Email Address: {{ user.email }}</h4>
</div>
</div>
<div class="row">
<div class="col-lg-12">
<h2 class="text-center">Charges</h2>
<table class="table table-striped">
<tr class="row">
<th>Description</th>
<th>Receipt Email</th>
<th>Amount</th>
<th>Card Info</th>
<th>Charge Status</th>
</tr>
{% for d in data_list %}
<tr class="row">
<td class="description">{{ d.description }} </td>
<td class="receipt_email"> {{ d.receipt_email}} </td>
<td class="amount">${{ d.amount }} </td>
<td class="source"> {{ d.source.brand }} ending in {{d.source.last4 }}</td>
<td class="status"> {{ d.outcome.seller_message}} </td>
</tr>
{% endfor %}
</table>

</div>
</div>
{% endblock %}