savvystripe/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from profiles import views as profile_views
from contact import views as contact_views
from checkout import views as checkout_views
from customers import views as customer_views
from checkout.models import Item, Service
from customers.models import stripeEvent
# import notifications.urls

urlpatterns = [
    url(r'^$', profile_views.home, name='home'),
    url(r'^accounts/', include('allauth.urls'), name='accounts'),
    # url(r'^carton/', include('carton.urls')),
    url(r'^about/$', profile_views.about, name='about'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^billing/$', customer_views.billing_view, name='billing'),
    url(r'^capture/$', checkout_views.capture, name='capture'),
    url(r'^add-to-cart/$', checkout_views.add_to_cart, name='add-to-cart' ),
    url(r'^add-subscription/$', checkout_views.add_subscription, name='add-subscription'),
    url(r'^remove-subscription/$', checkout_views.remove_subscription, name='remove-subscription'),
    # url(r'^cart-subscribe/$', checkout_views.cart_subscribe, name='cart-subscribe'),
    url(r'^unsubscribe/$', checkout_views.unsubscribe, name='ubsubscribe'),
    url(r'^subscribe/$', checkout_views.subscribe, name='subscribe'),
    url(r'^subscribe-card/$', checkout_views.subscribe_savecard, name='subscribe-card'),
    url(r'^remove-from-cart/$', checkout_views.remove_from_cart, name='remove-from-cart'),
    url(r'^before-checkout/$', checkout_views.before_checkout, name='before-checkout'),
    url(r'^cart/$', checkout_views.get_cart, name='cart'),
    url(r'^cart-total/$', checkout_views.get_cart_total, name='cart-total'),
    url(r'^checkout/$', checkout_views.checkout, name='checkout'),
    url(r'^hook/$', customer_views.event_hook, name='hook'),
    url(r'^checkout-thanks/$', checkout_views.checkoutThanks, name='checkoutThanks'),
    url(r'^contact/$', contact_views.contact, name='contact'),
    url(r'^contact/i', contact_views.contact, name='contact_track'),
    url(r'^dashboard/', include('dashboard.urls'), name='dashboard'),
    url(r'^domains/$', contact_views.searchDomains, name='domains'),
    url(r'^domain-results/$', contact_views.resultDomains, name='domain-results'),
    # url(r'^admin_dashboard/$', customer_views.admin_dashboard, name='admin_dashboard'),
    url(r'^events/$', customer_views.EventList, name='events'),
    url(r'^email_history/$', customer_views.email_history_view, name='email_history'),
    url(r'^inbox/notifications/', include("notifications.urls", namespace='notifications')) ,
    url(r'^articles/$', customer_views.KBListView.as_view(), name='articles'),
    url(r'^articles/(?P<pk>\d+)/$', customer_views.KBDetailView.as_view(), name='article'),
    url(r'^invoices/$', customer_views.my_invoices, name='invoices'),
    # url(r'^pixel/', include('pixel_tracker.urls'), name='pixels'),
    #url(r'^tracker/', include('django_pixels.urls', namespace="pixels")),
    url(r'^profile/$', profile_views.userProfile, name='profile'),
    # url(r'^sales/', include("sales.urls", namespace='sales')) ,
    url(r'^services/$', checkout_views.ServiceListView.as_view(), name='services'),
    url(r'^services/(?P<pk>\d+)/$', checkout_views.ServiceDetailView.as_view(), name='service'),
    # ex: /items/5/
    url(r'^my_services/$', customer_views.my_services, name='my_services'),
    url(r'^products/$', checkout_views.ItemListView.as_view(), name='items'),

    url(r'^products/(?P<pk>\d+)/$', checkout_views.ItemDetailView.as_view(), name='item'),
    # ex: /items/5/purchased/
    url(r'^tickets/', include("tickets.urls"), name='tickets') ,
    
]
    

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

savvystripe/sales/urls.py
from django.conf.urls import *
from sales import views

urlpatterns = [
    url(r'^charge/$', views.charge, name="charge"),
]

savvystripe/contact/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.sites.models import Site
from django.db.models import signals
from notifications import models as notification
import subprocess
# Create your models here.

# def create_notice_types(app, created_models, verbosity, **kwargs):
#     notification.create_notice_type("new_comment", "Comment posted", "A comment has been posted")
# signals.post_syncdb.connect(create_notice_types, sender=notification)

def whois(domain):     
    answer = subprocess.Popen(['whois', domain], stdout=subprocess.PIPE).communicate()          
    return answer  



def new_comment(sender, instance, created, **kwargs):
    # remove this if-block if you want notifications for comment edit too
    if not created:
        return None

    context = {
        'comment': instance,
        'site': Site.objects.get_current(),
    }
    recipients = []

    # add all users who commented the same object to recipients
    for comment in instance.__class__.objects.for_model(instance.content_object):
        if comment.user not in recipients and comment.user != instance.user:
            recipients.append(comment.user)

    # if the commented object is a user then notify him as well
    if isinstance(instance.content_object, models.get_model('auth', 'User')):
        # if he his the one who posts the comment then don't add him to recipients
        if instance.content_object != instance.user and instance.content_object not in recipients:
            recipients.append(instance.content_object)

    notification.send(recipients, 'new_comment', context)

signals.post_save.connect(new_comment, sender=('comments', 'Comment'))

savvystripe/contact/forms.py
from django import forms
from django.http import HttpResponse, request 
from django.shortcuts import render, render_to_response
from .models import whois 
import subprocess

class contactForm(forms.Form):
	name = forms.CharField(required=True, max_length=100, help_text="100 characters max")
	email = forms.EmailField(required=True)
	comment = forms.CharField(required=True, widget=forms.Textarea)

# class domainForm(forms.Form):
# 	placeholder
class WhoisForm(forms.Form):     
	domainname = forms.CharField(max_length=100)      

savvystripe/contact/views.py
from django.shortcuts import render, render_to_response
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import stripe
from profiles.models import userStripe
import json
from django.http import HttpResponse, request
from django import forms 
from .models import whois
from .forms import WhoisForm
import subprocess
#from django_pixels import utils, handlers
from django.core.urlresolvers import reverse
from snowplow_tracker import Subject, Tracker, Emitter

stripe.api_key = settings.STRIPE_SECRET_KEY
from .forms import contactForm

# Create your views here.
#@login_required
def contact(request):
	title = 'Contact'
	form = contactForm(request.POST or None)
	confirm_message = None
	e = Emitter("192.168.2.133:8090/contact")
        tracker = Tracker(e , namespace="sdp", app_id="sdp-11", encode_base64=False)
	

	if form.is_valid():
		name = form.cleaned_data['name']
		comment = form.cleaned_data['comment']
		subject = 'Message from Mysite.com'
		message = '%s %s' % (comment, name)
		emailFrom = form.cleaned_data['email']
		# emailTo = [settings.EMAIL_HOST_USER]
		emailTo = ['admin@savantdigital.net']
		send_mail(subject, message, emailFrom, emailTo, fail_silently=True,)
		title = 'Thanks!'
		confirm_message = 'Thanks for the message, we will get right back to you.'
		form = None
		tracker.track_page_view("192.168.2.133:8090/contact")

	context = {'title': title,'form': form, 'confirm_message': confirm_message, }	
	template = 'contact.html'
	return render(request, template, context)

@login_required
def searchDomains(request):
	title = 'Search Domains'
	form = WhoisForm(request.POST or None)
	confirm_message = None

	if form.is_valid():
		domain = form.cleaned_data['domainname']
		answer = whois(domain)
		a = str(answer[0])
		b = a.decode('utf-8').split('\n')
		registrar = b[8]
		domname = b[7]
		ns1 = b[12]
		ns2 = b[13]
		ns3 = b[14]
		status = b[16]
		updated = b[17]
		created = b[18]
		expiration = b[19]
		# registrant info
		reg_name = b[70]
		reg_org = b[71]
		reg_st = b[72]
		reg_st2 = b[73]
		reg_city = b[74]
		reg_state = b[75]
		reg_zip = b[76]
		reg_country = b[77]
		reg_phone = b[78]
		reg_email = b[82]
		# admin info
		adm_name = b[84]
		adm_org = b[85]
		adm_st = b[86]
		adm_st2 = b[87]
		adm_city = b[88]
		adm_state = b[89]
		adm_zip = b[90]
		adm_country = b[91]
		adm_phone = b[92]
		adm_email = b[96]
		# tech info
		tech_name = b[98]
		tech_org = b[99]
		tech_st = b[100]
		tech_st2 = b[101]
		tech_city = b[102]
		tech_state = b[103]
		tech_zip = b[104]
		tech_country = b[105]
		tech_phone = b[106]
		tech_email = b[110]
		d = dict([
			("registrar", registrar),
			("domname", domname), 
			("ns1", ns1),  
			("ns2", ns2),
			("ns3", ns3), 
			("status", status),
			("updated", updated),
			("created", created),
			("expiration", expiration),
			("reg_name", reg_name),
			("reg_org", reg_org ),
			("reg_st", reg_st) ,
			("reg_st2", reg_st2), 
			("reg_city", reg_city), 
			("reg_state", reg_state), 
			("reg_zip", reg_zip), 
			("reg_country", reg_country), 
			("reg_phone", reg_phone), 
			("reg_email", reg_email), 
			("adm_name", adm_name),
			("adm_org", adm_org), 
			("adm_st", adm_st), 
			("adm_st2", adm_st2), 
			("adm_city", adm_city),  
			("adm_state", adm_state),  
			("adm_zip", adm_zip), 
			("adm_country", adm_country), 
			("adm_phone", adm_phone), 
			("adm_email", adm_email), 
			("tech_name", tech_name), 
			("tech_org", tech_org),
			("tech_st", tech_st), 
			("tech_st2", tech_st2), 
			("tech_city", tech_city), 
			("tech_state", tech_state), 
			("tech_zip", tech_zip), 
			("tech_country", tech_country), 
			("tech_phone", tech_phone),
			("tech_email", tech_email),
		   ])
		

	context = {'title': title, 'form':form, 'confirm_message': confirm_message}
	template = 'search-domains.html'
	return render(request, template, context)


@login_required
def resultDomains(request):
	title = 'Domain Results'
	form = WhoisForm(request.POST or None)
	confirm_message = None

	if form.is_valid():
		domain = form.cleaned_data['domainname']
		answer = whois(domain)
		a = str(answer[0])
		b = a.decode('utf-8').split('\n')
		registrar = b[8]
		domname = b[7]
		ns1 = b[12]
		ns2 = b[13]
		ns3 = b[14]
		status = b[16]
		updated = b[17]
		created = b[18]
		expiration = b[19]
		# registrant info
		reg_name = b[70]
		reg_org = b[71]
		reg_st = b[72]
		reg_st2 = b[73]
		reg_city = b[74]
		reg_state = b[75]
		reg_zip = b[76]
		reg_country = b[77]
		reg_phone = b[78]
		reg_email = b[82]
		# admin info
		adm_name = b[84]
		adm_org = b[85]
		adm_st = b[86]
		adm_st2 = b[87]
		adm_city = b[88]
		adm_state = b[89]
		adm_zip = b[90]
		adm_country = b[91]
		adm_phone = b[92]
		adm_email = b[96]
		# tech info
		tech_name = b[98]
		tech_org = b[99]
		tech_st = b[100]
		tech_st2 = b[101]
		tech_city = b[102]
		tech_state = b[103]
		tech_zip = b[104]
		tech_country = b[105]
		tech_phone = b[106]
		tech_email = b[110]
		d = dict([
			("registrar", registrar),
			("domname", domname), 
			("ns1", ns1),  
			("ns2", ns2),
			("ns3", ns3), 
			("status", status),
			("updated", updated),
			("created", created),
			("expiration", expiration),
			("reg_name", reg_name),
			("reg_org", reg_org ),
			("reg_st", reg_st) ,
			("reg_st2", reg_st2), 
			("reg_city", reg_city), 
			("reg_state", reg_state), 
			("reg_zip", reg_zip), 
			("reg_country", reg_country), 
			("reg_phone", reg_phone), 
			("reg_email", reg_email), 
			("adm_name", adm_name),
			("adm_org", adm_org), 
			("adm_st", adm_st), 
			("adm_st2", adm_st2), 
			("adm_city", adm_city),  
			("adm_state", adm_state),  
			("adm_zip", adm_zip), 
			("adm_country", adm_country), 
			("adm_phone", adm_phone), 
			("adm_email", adm_email), 
			("tech_name", tech_name), 
			("tech_org", tech_org),
			("tech_st", tech_st), 
			("tech_st2", tech_st2), 
			("tech_city", tech_city), 
			("tech_state", tech_state), 
			("tech_zip", tech_zip), 
			("tech_country", tech_country), 
			("tech_phone", tech_phone),
			("tech_email", tech_email),
		   ])
		

	context = {'title': title, 'form':form, 'confirm_message': confirm_message, 'answer': d}
	template = 'domains.html'
	return render(request, template, context)


#def track_emails(request):
#	tracking_url = reverse('pixels:pixel')
#	pixel_ = utils.compose_pixel_url(tracking_url, 1)
#	handlers.register(1, track_emails)
#	response = HttpResponse(pixel_, content_type='image/gif')
#	return render(request, response)
def tracker(request):
	tracker = Tracker( Emitter("payments.savantdigital.net") , namespace="sdp", app_id="sdp-11", encode_base64=False)
	return render(request, response, context)

savvystripe/contact/templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1> {{ title }} </h1>
{% if confirm_message %}
<p> {{ confirm_message }}</p>
{% endif %}
{% if form %}
<form method='POST' action=''> {% csrf_token %}
{{ form|crispy }}
<input type='submit' value='Submit Form' class='btn btn-default' />
</form>
{% endif %}
</div>
</div>
{% endblock %}

savvystripe/contact/templates/domains.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class='row'>
<div class='col-lg-8 col-lg-offset-2'>
<h1> {{ title }} </h1>
{% if confirm_message %}
<p> {{ confirm_message }}</p>
{% endif %}
{% if form %}
<form method='POST' action=''> {% csrf_token %}
{{ form|crispy }}
<input type='submit' value='Submit Form' class='btn btn-default' />
</form>
<h3> Search Results</h3>
<div class="table-responsive">
<table class="table table-bordered table-hover text-center">
</tr>
<tr class="row">
<td colspan="2" class="text-left"><b>Registrar Information:</b></td>
</tr>
<tr class="row">
<td>{{answer.registrar}}</td>
</tr>
<tr class="row">
<td>{{answer.domname}}</td>
</tr>
<tr class="row">
<td>{{answer.ns1}}</td>
</tr>
<tr class="row">
<td>{{answer.ns2}}</td>
</tr>
<tr class="row">
<td>{{answer.ns3}}</td>
</tr>
<tr class="row">
<td>{{answer.status}}</td>
</tr>
<tr class="row">
<td>{{answer.updated}}</td>
</tr>
<tr class="row">
<td>{{answer.created}}</td>
</tr>
<tr class="row">
<td>{{answer.expiration}}</td>
</tr>
<tr class="row">
<td colspan="2" class="text-left"><b>Registrant Contact Information:</b></td>
</tr>
<tr class="row">
<td>{{answer.reg_name}}</td>
</tr>
<tr class="row">
<td>{{answer.reg_org}}</td>
</tr>
<tr class="row">
<td>{{answer.reg_st}} <br>
	{{answer.reg_st2}}</td>
</tr>
<tr class="row">
<td>{{answer.reg_city}}</td>
</tr>
<tr class="row">
<td>{{answer.reg_state}}</td>
</tr>
<tr class="row">
<td>{{answer.reg_zip}}</td>
</tr>
<tr class="row">
<td>{{answer.reg_country}}</td>
</tr>
<tr class="row">
<td>{{answer.reg_phone}}</td>
</tr>
<tr class="row">
<td>{{answer.reg_email}}</td>
</tr>
<tr class="row">
<td colspan="2" class="text-left"><b>Administrator Contact Information:</b></td>
</tr>
<!-- end registrant area -->
<tr class="row">
<td>{{answer.adm_name}}</td>
</tr>
<tr class="row">
<td>{{answer.adm_org}}</td>
</tr>
<tr class="row">
<td>{{answer.adm_st}} <br>
	{{answer.adm_st2}}</td>
</tr>
<tr class="row">
<td>{{answer.adm_city}}</td>
</tr>
<tr class="row">
<td>{{answer.adm_state}}</td>
</tr>
<tr class="row">
<td>{{answer.adm_zip}}</td>
</tr>
<tr class="row">
<td>{{answer.adm_country}}</td>
</tr>
<tr class="row">
<td>{{answer.adm_phone}}</td>
</tr>
<tr class="row">
<td>{{answer.adm_email}}</td>
</tr>
<tr class="row">
<td colspan="2" class="text-left"><b>Technician Contact Information:</b></td>
</tr>
<!--  end admin area -->
<tr class="row">
<td>{{answer.tech_name}}</td>
</tr>
<tr class="row">
<td>{{answer.tech_org}}</td>
</tr>
<tr class="row">
<td>{{answer.tech_st}} <br>
	{{answer.tech_st2}}</td>
</tr>
<tr class="row">
<td>{{answer.tech_city}}</td>
</tr>
<tr class="row">
<td>{{answer.tech_state}}</td>
</tr>
<tr class="row">
<td>{{answer.tech_zip}}</td>
</tr>
<tr class="row">
<td>{{answer.tech_country}}</td>
</tr>
<tr class="row">
<td>{{answer.tech_phone}}</td>
</tr>
<tr class="row">
<td>{{answer.tech_email}}</td>
</tr>
</table>
</div>

{% endif %}
</div>
</div>
{% endblock %}
 

savvystripe/contact/templates/search-domains.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class='row'>
<div class='col-lg-8 col-lg-offset-2'>
<!-- <h1> {{ title }} </h1>
{% if confirm_message %}
<p> {{ confirm_message }}</p>
{% endif %} -->
<!-- {% if form %}
<form method='POST' action=''> {% csrf_token %}
{{ form|crispy }}
<input type='submit' value='Submit Form' class='btn btn-default' />
</form> -->
<h1>Search Domains</h1>
<div class="">
    		<form action="{% url 'domain-results' %}" method="post"> {% csrf_token %}
    		<label class="text-left">Domain Name*</label>
    		<input class="textinput textInput form-control" id="id_domainname" maxlength="100" name="domainname" value="" required="" type="text">
    		<input type="submit" value="Submit Form" class="btn btn-default text-left">
			</form>
			</div>

{% endif %}
{% endblock %}